# check=skip=SecretsUsedInArgOrEnv
# Dockerfile para Render
FROM n8nio/n8n:latest


ENV N8N_BASIC_AUTH_ACTIVE=true
ENV N8N_BASIC_AUTH_USER=user
ENV N8N_BASIC_AUTH_PASSWORD=password
ENV N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS=true


ENV DB_TYPE=postgresdb
ENV DB_POSTGRESDB_DATABASE=n8n
ENV DB_POSTGRESDB_HOST=<RENDER_POSTGRES_HOST>
ENV DB_POSTGRESDB_PORT=5432
ENV DB_POSTGRESDB_USER=<RENDER_POSTGRES_USER>
ENV DB_POSTGRESDB_PASSWORD=<RENDER_POSTGRES_PASSWORD>

# Puerto que usa n8n
EXPOSE 5678

# Comando de inicio (opcional, la imagen ya lo tiene)
CMD ["n8n", "start"]
